# Generated by Django 4.2.7 on 2025-10-27 22:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="cpf",
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="trial_ends_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="plan",
            field=models.CharField(
                choices=[
                    ("free", "Free (7 dias teste)"),
                    ("pro", "Pro - $29/mês"),
                    ("premium", "Premium - $99/mês"),
                ],
                default="free",
                max_length=10,
            ),
        ),
    ]
