# Generated by Django 4.2.7 on 2025-10-27 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BotConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("exchange", models.CharField(max_length=20)),
                ("symbols", models.JSONField(default=list)),
                ("capital", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "strategy",
                    models.CharField(
                        choices=[
                            ("mean_reversion", "Mean Reversion"),
                            ("trend_following", "Trend Following"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timeframe", models.CharField(default="15m", max_length=5)),
                (
                    "stop_loss_percent",
                    models.DecimalField(decimal_places=3, default=1.5, max_digits=5),
                ),
                (
                    "take_profit_percent",
                    models.DecimalField(decimal_places=3, default=3.0, max_digits=5),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bot_configs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "bot_configurations",
            },
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exchange", models.CharField(max_length=20)),
                ("symbol", models.CharField(max_length=20)),
                ("side", models.CharField(max_length=4)),
                ("entry_price", models.DecimalField(decimal_places=8, max_digits=20)),
                (
                    "exit_price",
                    models.DecimalField(decimal_places=8, max_digits=20, null=True),
                ),
                ("quantity", models.DecimalField(decimal_places=8, max_digits=20)),
                (
                    "profit_loss",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "profit_loss_percent",
                    models.DecimalField(decimal_places=2, max_digits=8, null=True),
                ),
                ("entry_time", models.DateTimeField()),
                ("exit_time", models.DateTimeField(null=True)),
                ("status", models.CharField(default="open", max_length=10)),
                (
                    "bot_config",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bots.botconfiguration",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "trades",
                "ordering": ["-entry_time"],
            },
        ),
    ]
