# Generated by Django 4.2.7 on 2025-10-29 23:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bots", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trade",
            name="highest_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                help_text="Preço mais alto alcançado (para trailing stop)",
                max_digits=20,
                null=True,
            ),
        ),
    ]
